import type { Metadata } from "next";
import "@fontsource-variable/space-grotesk";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico?v2" sizes="any" />
      </head>
      <body>{children}</body>
    </html>
  );
}
